# Generated by Django 4.2.4 on 2023-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_queryhistory_cadastre_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
    ]
