# Generated by Django 4.2.4 on 2023-09-04 08:00

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_queryhistory_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=7, validators=[api.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=7, validators=[api.validators.validate_longitude]),
        ),
    ]
