# Generated by Django 4.2.4 on 2023-09-04 08:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_queryhistory_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='cadastre_number',
            field=models.CharField(max_length=19, unique=True, validators=[api.validators.validate_cadastre_number]),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='latitude',
            field=models.FloatField(validators=[api.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='longitude',
            field=models.FloatField(validators=[api.validators.validate_longitude]),
        ),
    ]
